# Generated by Django 3.2.3 on 2021-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_set',
            name='created_by',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
