# Generated by Django 3.2.3 on 2021-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_card_set_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='study_more',
            field=models.BooleanField(default=False),
        ),
    ]
